
package org.una.tramites.loaders;


public enum Permisos {
    USUARIO_MODIFICAR("USU2"),
    USUARIO_INACTIVAR("USU3"),
    USUARIO_CONSULTAR("USU4"),
    USUARIO_CONSULTAR_TODO("USU5"),
    USUARIO_ELIMINAR("USU6"), 
    USUARIO_ELIMINAR_TODO("USU7"),
    
    CLIENTE_CREAR("CLI1"),
    CLIENTE_MODIFICAR("CLI2"),
    CLIENTE_CONSULTAR("CLI3"),
    CLIENTE_CONSULTAR_TODO("CLI4"),
    CLIENTE_ELIMINAR("CLI5"), 
    CLIENTE_ELIMINAR_TODO("CLI6"),
    
    NOTA_CREAR("NOT1"),
    NOTA_MODIFICAR("NOT2"),
    NOTA_CONSULTAR("NOT3"),
    NOTA_CONSULTAR_TODO("NOT4"),
    NOTA_ELIMINAR("NOT5"), 
    NOTA_ELIMINAR_TODO("NOT6"),
    
    ARCHIVO_CREAR("ARC1"),
    ARCHIVO_MODIFICAR("ARC2"),
    ARCHIVO_CONSULTAR("ARC3"),
    ARCHIVO_CONSULTAR_TODO("ARC4"),
    ARCHIVO_ELIMINAR("ARC5"), 
    ARCHIVO_ELIMINAR_TODO("ARC6"),
    
    DEPARTAMENTO_CREAR("DEP1"),
    DEPARTAMENTO_MODIFICAR("DEP2"),
    DEPARTAMENTO_INACTIVAR("DEP3"),
    DEPARTAMENTO_CONSULTAR("DEP4"),
    DEPARTAMENTO_CONSULTAR_TODO("DEP5"),
    
    TRAMITE_REGISTRAR("TRA1"),
    TRAMITE_MODIFICAR("TRA2"),
    TRAMITE_INACTIVAR("TRA3"),
    TRAMITE_FINALIZAR("TRA4"),
    TRAMITE_CONSULTAR("TRA5"),
    TRAMITE_CONSULTAR_TODO("TRA6"),
    TRAMITE_DISEÑAR("TRD1"),
    
    TRAMITE_ESTADO_REGISTRAR("TE1"),
    TRAMITE_ESTADO_MODIFICAR("TE2"),
    TRAMITE_ESTADO_FINALIZAR("TE3"),
    TRAMITE_ESTADO_CONSULTAR("TE4"),
    TRAMITE_ESTADO_CONSULTAR_TODO("TE5"),
    
    TRAMITE_TIPO_REGISTRAR("TT1"),
    TRAMITE_TIPO_MODIFICAR("TT2"),
    TRAMITE_TIPO_FINALIZAR("TT3"),
    TRAMITE_TIPO_CONSULTAR("TT4"),
    TRAMITE_TIPO_CONSULTAR_TODO("TT5"),
    TRAMITE_TIPO_ESTADO("TT6"),
    
    TRAN_CREAR("TN1"),
    TRAN_MODIFICAR("TN2"),
    TRAN__ELIMINAR("TN3"),
    TRAN_CONSULTAR("TN4"),
    
    
    VARIACION_CREAR("VAR1"),
    VARIACION_MODIFICAR("VAR2"),
    VARIACION_INACTIVAR("VAR3"),
    VARIACION_CONSULTAR("VAR4"),
    VARIACION_CONSULTAR_TODO("VAR5"),
    
    REQUISITO_CREAR("REQ1"),
    REQUISITO_MODIFICAR("REQ2"),
    REQUISITO_INACTIVAR("REQ3"),
    REQUISITO_CONSULTAR("REQ4"),
    REQUISITO_CONSULTAR_TODO("REQ5"),
    REQUISITO_ELIMINAR("REQ6"),
    REQUISITO_ELIMINAR_TODO("REQ5"),
    
    REQUISITO_PRECE_CREAR("RP1"),
    REQUISITO_PRECE_MODIFICAR("RP2"),
    REQUISITO_PRECE_CONSULTAR("RP3"),
    REQUISITO_PRECE_TODO("RP4"),
    REQUISITO_PRECE_ELIMINAR("RP5"),
    REQUISITO_PRECE_ELIMINAR_TODO("RP6"),
    
    PARAMETRO_CREAR("PAR1"),
    PARAMETRO_MODIFICAR("PAR2"),
    PARAMETRO_INACTIVAR("PAR3"),
    PARAMETRO_CONSULTAR("PAR4"),
    
    PERMISO_OTORGADO_CREAR("PO1"),
    PERMISO_OTORGADO_MODIFICAR("PO2"),
    PERMISO_OTORGADO_CONSULTAR("PO3"),
    PERMISO_OTORGADO_ELIMINAR("PO4"),
    PERMISO_OTORGADO_ELIMINAR_TODO("PO5"),
    
    PERMISO_CREAR("PER1"),
    PERMISO_MODIFICAR("PER2"),
    PERMISO_INACTIVAR("PER3"),
    PERMISO_CONSULTAR("PER4"),
    PERMISO_ELIMINAR("PER5"),
    PERMISO_CONSULTAR_TODO("PER6"),
    PERMISO_ELIMINAR_TODO("PER7");
    private String codigo;

    Permisos(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }
}

