
package org.una.tramites.loaders;


public enum Permisos {
    USUARIO_CREAR("USU1"),
    USUARIO_MODIFICAR("USU2"),
    USUARIO_INACTIVAR("USU3"),
    USUARIO_CONSULTAR("USU4"),
    USUARIO_CONSULTAR_TODO("USU5"),
    USUARIO_ELIMINAR("USU6"), 
    USUARIO_ELIMINAR_TODO("USU7"),
    DEPARTAMENTO_CREAR("DEP1"),
    DEPARTAMENTO_MODIFICAR("DEP2"),
    DEPARTAMENTO_INACTIVAR("DEP3"),
    DEPARTAMENTO_CONSULTAR("DEP4"),
    TRAMITE_REGISTRAR("TRA1"),
    TRAMITE_MODIFICAR("TRA2"),
    TRAMITE_INACTIVAR("TRA3"),
    TRAMITE_FINALIZAR("TRA4"),
    TRAMITE_CONSULTAR("TRA5"),
    TRAMITE_CONSULTAR_TODO("TRA6"),
    TRAMITE_DISEÑAR("TRD1"),
    VARIACION_CREAR("VAR1"),
    VARIACION_MODIFICAR("VAR2"),
    VARIACION_INACTIVAR("VAR3"),
    VARIACION_CONSULTAR("VAR4"),
    REQUISITO_CREAR("REQ1"),
    REQUISITO_MODIFICAR("REQ2"),
    REQUISITO_INACTIVAR("REQ3"),
    REQUISITO_CONSULTAR("REQ4"),
    PARAMETRO_CREAR("PAR1"),
    PARAMETRO_MODIFICAR("PAR2"),
    PARAMETRO_INACTIVAR("PAR3"),
    PARAMETRO_CONSULTAR("PAR4"),
    PERMISO_CREAR("PER1"),
    PERMISO_MODIFICAR("PER2"),
    PERMISO_INACTIVAR("PER3"),
    PERMISO_CONSULTAR("PER4");
    private String codigo;

    Permisos(String codigo) {
        this.codigo = codigo;
    }

    public String getCodigo() {
        return codigo;
    }
}

